import { NextResponse } from 'next/server';
import connectToDatabase from '@/lib/db';
import TeamProject from '@/models/TeamProject';
import { getMonthFromDate } from '@/lib/dateUtils';

const SEED_TEAM_PROJECTS = [
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-10-02',
    month: 'October',
    profileName: 'logokarigor',
    clientUserId: 'ellieslp',
    orderNumber: 'FO11498FB3E45',
    amount: 250,
    netAmount: 200,
    assignedMembers: ['Need Requirements'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-09-10',
    remark: 'Mutual Cancel From Support',
    orderStatus: 'Cancel',
    sheetLink: 'ellieslp_Logokarigar',
    teamName: 'EleSquad',
    percentage: 50,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-08-29',
    month: 'August',
    profileName: 'dev_verse',
    clientUserId: 'fsimaging',
    orderNumber: 'FO82A14FFD6C4',
    amount: 350,
    netAmount: 280,
    assignedMembers: ['Shuvo'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-09-01',
    remark: '',
    orderStatus: 'Delivered',
    sheetLink: 'FO82A14FFD6C4',
    teamName: 'EleSquad',
    percentage: 70,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-08-28',
    month: 'August',
    profileName: 'miahs05',
    clientUserId: 'ladytt09',
    orderNumber: 'FO41C0D570D84',
    amount: 280,
    netAmount: 224,
    assignedMembers: ['Jasmin'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-09-04',
    remark: '',
    orderStatus: 'Delivered',
    sheetLink: 'ladytt09_FO41C0D67',
    teamName: 'EleSquad',
    percentage: 56,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Sahid Bappi',
    assignDate: '2026-09-01',
    month: 'September',
    profileName: 'codepremier',
    clientUserId: 'happibola',
    orderNumber: 'FO42313B96006',
    amount: 120,
    netAmount: 96,
    assignedMembers: ['Naim'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-09-05',
    remark: 'Repeat Order',
    orderStatus: 'Delivered',
    sheetLink: '',
    teamName: 'EleSquad',
    percentage: 24,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-08-31',
    month: 'August',
    profileName: 'wpstellar_Fiverr',
    clientUserId: 'yossisalamon',
    orderNumber: 'FO42A1B9719C8',
    amount: 220,
    netAmount: 176,
    assignedMembers: ['Shuvo'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-09-07',
    remark: 'Repeat Order',
    orderStatus: 'Delivered',
    sheetLink: '',
    teamName: 'EleSquad',
    percentage: 44,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-08-19',
    month: 'August',
    profileName: 'miahs05',
    clientUserId: 'jennalloyd',
    orderNumber: 'FO32309EA1387',
    amount: 290,
    netAmount: 232,
    assignedMembers: ['Akash'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-09-08',
    remark: '',
    orderStatus: 'Delivered',
    sheetLink: 'Wordpress_jennalloy',
    teamName: 'EleSquad',
    percentage: 58,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Md Rone Miah',
    assignDate: '2026-09-07',
    month: 'September',
    profileName: 'wpstellar',
    clientUserId: 'hamdy7',
    orderNumber: 'FO1150E81BD45',
    amount: 60,
    netAmount: 48,
    assignedMembers: ['Jasmin'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-09-08',
    remark: 'Repeat Order',
    orderStatus: 'Delivered',
    sheetLink: 'WordPress_hamdy7',
    teamName: 'EleSquad',
    percentage: 12,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Md Rone Miah',
    assignDate: '2026-09-03',
    month: 'September',
    profileName: 'wpstellar_Fiverr',
    clientUserId: 'mrsanyoo',
    orderNumber: 'FO52A197790C7',
    amount: 200,
    netAmount: 160,
    assignedMembers: ['Shuvo'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-09-09',
    remark: 'Repeat Order',
    orderStatus: 'Delivered',
    sheetLink: 'WordPress_mrsanyo',
    teamName: 'EleSquad',
    percentage: 40,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-08-25',
    month: 'August',
    profileName: 'smtechnology',
    clientUserId: 'hphamily',
    orderNumber: 'FO5230E23C905',
    amount: 190,
    netAmount: 152,
    assignedMembers: ['Alireja'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-09-09',
    remark: '',
    orderStatus: 'Delivered',
    sheetLink: 'hphamily || FO5230E',
    teamName: 'EleSquad',
    percentage: 38,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Chayon Saha',
    assignDate: '2026-09-05',
    month: 'September',
    profileName: 'miahs05',
    clientUserId: 'robert_newby',
    orderNumber: 'FO71C12776F81',
    amount: 150,
    netAmount: 120,
    assignedMembers: ['Fahim'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-09-09',
    remark: '',
    orderStatus: 'Delivered',
    sheetLink: 'WordPress_robert',
    teamName: 'EleSquad',
    percentage: 30,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Chayon Saha',
    assignDate: '2026-09-04',
    month: 'September',
    profileName: 'miahs05',
    clientUserId: 'eyupthai',
    orderNumber: 'FO32315ACE08',
    amount: 80,
    netAmount: 64,
    assignedMembers: ['Alireja'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-09-12',
    remark: '',
    orderStatus: 'Delivered',
    sheetLink: 'WordPress_eyupthai',
    teamName: 'EleSquad',
    percentage: 16,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Md Isme Ajam',
    assignDate: '2026-09-10',
    month: 'September',
    profileName: 'miahs05',
    clientUserId: 'jamshedtai2023',
    orderNumber: 'FO4231ADC8606',
    amount: 120,
    netAmount: 96,
    assignedMembers: ['Jasmin'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-09-12',
    remark: 'Repeat Order',
    orderStatus: 'Delivered',
    sheetLink: '',
    teamName: 'EleSquad',
    percentage: 24,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-07-09',
    month: 'July',
    profileName: 'nextstack_fiverr',
    clientUserId: 'nisarahmad105',
    orderNumber: 'FO829E374B1C4',
    amount: 100,
    netAmount: 80,
    assignedMembers: ['Jasmin'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-07-24',
    remark: 'Repeat Order',
    orderStatus: 'Wip',
    sheetLink: '',
    teamName: 'EleSquad',
    percentage: 20,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-07-16',
    month: 'July',
    profileName: 'Miahs05_Fiverr',
    clientUserId: 'khan_123456782',
    orderNumber: 'FO522EDDD1E85',
    amount: 275,
    netAmount: 220,
    assignedMembers: ['Shihad', 'Mahin'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-07-31',
    remark: '',
    orderStatus: 'Wip',
    sheetLink: 'Fiverr-Inbox-07-16-20',
    teamName: 'EleSquad',
    percentage: 55,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-08-03',
    month: 'August',
    profileName: 'W3B_Hive_Fiverr',
    clientUserId: 'mgrades',
    orderNumber: 'FO522FC7C5005',
    amount: 260,
    netAmount: 208,
    assignedMembers: ['Shuvo', 'Jasmin'],
    estimatedDeliveryDate: '2026-09-20',
    deliveryDate: '',
    remark: '',
    orderStatus: 'Wip',
    sheetLink: 'W3b_hive_mgrades',
    teamName: 'EleSquad',
    percentage: 52,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-08-15',
    month: 'August',
    profileName: 'wpstellar',
    clientUserId: 'michaelwhale753',
    orderNumber: 'FO17015FF481',
    amount: 290,
    netAmount: 232,
    assignedMembers: ['Need Requirements'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-08-25',
    remark: '',
    orderStatus: 'NRA',
    sheetLink: 'Wordpress_michaelw',
    teamName: 'EleSquad',
    percentage: 58,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-08-19',
    month: 'August',
    profileName: 'W3B_Hive_Fiverr',
    clientUserId: 'beck9barnes',
    orderNumber: 'FO61BF441A582',
    amount: 75,
    netAmount: 60,
    assignedMembers: ['Jasmin'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-08-23',
    remark: 'Repeat Order',
    orderStatus: 'Wip',
    sheetLink: '',
    teamName: 'EleSquad',
    percentage: 15,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-07-04',
    month: 'July',
    profileName: 'miahs05',
    clientUserId: 'nathaliakue',
    orderNumber: 'FO830D83E6746',
    amount: 245,
    netAmount: 196,
    assignedMembers: ['Akash'],
    estimatedDeliveryDate: '',
    deliveryDate: '2026-07-11',
    remark: '',
    orderStatus: 'Wip',
    sheetLink: '',
    teamName: 'EleSquad',
    percentage: 49,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'C_Forward_SMT Sales',
    assignDate: '2026-08-25',
    month: 'August',
    profileName: 'smtechnology',
    clientUserId: 'artexhibits',
    orderNumber: 'FO62A116C25C6',
    amount: 165,
    netAmount: 132,
    assignedMembers: ['Akash'],
    estimatedDeliveryDate: '2026-09-18',
    deliveryDate: '2026-09-15',
    remark: 'Repeat Order',
    orderStatus: 'Wip',
    sheetLink: 'existing',
    teamName: 'EleSquad',
    percentage: 33,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Pinak Chakrabarti',
    assignDate: '2026-09-06',
    month: 'September',
    profileName: 'w3b_hive',
    clientUserId: 'aricinhom',
    orderNumber: 'FO1E0971BA43',
    amount: 480,
    netAmount: 384,
    assignedMembers: ['Naim'],
    estimatedDeliveryDate: '2026-09-14',
    deliveryDate: '2026-09-20',
    remark: '',
    orderStatus: 'Wip',
    sheetLink: 'aricinhom || W3bhiv',
    teamName: 'EleSquad',
    percentage: 96,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Md. Salman Dewan',
    assignDate: '2026-09-06',
    month: 'September',
    profileName: 'uidesignli',
    clientUserId: 'tifffers687',
    orderNumber: 'FO2150E62B9C4',
    amount: 150,
    netAmount: 120,
    assignedMembers: ['Shuvo'],
    estimatedDeliveryDate: '2026-09-20',
    deliveryDate: '2026-09-21',
    remark: 'Repeat Order',
    orderStatus: 'Wip',
    sheetLink: 'Wordpress and V&',
    teamName: 'EleSquad',
    percentage: 30,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Md Rone Miah',
    assignDate: '2026-09-07',
    month: 'September',
    profileName: 'wpstellar',
    clientUserId: 'hamdy7',
    orderNumber: 'FO11C13486987',
    amount: 85,
    netAmount: 68,
    assignedMembers: ['Jasmin'],
    estimatedDeliveryDate: '2026-09-17',
    deliveryDate: '',
    remark: 'Repeat Order',
    orderStatus: 'Wip',
    sheetLink: 'WordPress_hamdy7',
    teamName: 'EleSquad',
    percentage: 17,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Chayon Saha',
    assignDate: '2026-09-07',
    month: 'September',
    profileName: 'miahs05',
    clientUserId: 'jamshedtai2023',
    orderNumber: 'FO32318750687',
    amount: 250,
    netAmount: 200,
    assignedMembers: ['Jasmin'],
    estimatedDeliveryDate: '2026-09-15',
    deliveryDate: '2026-09-17',
    remark: 'Repeat Order',
    orderStatus: 'Wip',
    sheetLink: '',
    teamName: 'EleSquad',
    percentage: 50,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Md Rone Miah',
    assignDate: '2026-09-09',
    month: 'September',
    profileName: 'wpstellar',
    clientUserId: 'gilbertomonn273',
    orderNumber: 'FO5231A553D85',
    amount: 350,
    netAmount: 280,
    assignedMembers: ['Mahin', 'Fahim'],
    estimatedDeliveryDate: '2026-09-17',
    deliveryDate: '2026-09-16',
    remark: '',
    orderStatus: 'Wip',
    sheetLink: 'WordPress_gilbertom',
    teamName: 'EleSquad',
    percentage: 70,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Md. Salman Dewan',
    assignDate: '2026-09-11',
    month: 'September',
    profileName: 'miahs06',
    clientUserId: 'darlanjoubert',
    orderNumber: 'FO1705781001',
    amount: 129,
    netAmount: 103.20,
    assignedMembers: ['Alireja'],
    estimatedDeliveryDate: '2026-09-15',
    deliveryDate: '',
    remark: '',
    orderStatus: 'Wip',
    sheetLink: 'WordPress_Miahs05',
    teamName: 'EleSquad',
    percentage: 25.80,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Nur Istiak Araf',
    assignDate: '2026-09-11',
    month: 'September',
    profileName: 'mind_touch',
    clientUserId: 'lalofak',
    orderNumber: 'FO3E0AECE641',
    amount: 100,
    netAmount: 80,
    assignedMembers: ['Jasmin'],
    estimatedDeliveryDate: '2026-09-16',
    deliveryDate: '2026-09-17',
    remark: 'Repeat Order',
    orderStatus: 'Wip',
    sheetLink: '',
    teamName: 'EleSquad',
    percentage: 20,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
  {
    salesPerson: 'Chayon Saha',
    assignDate: '2026-09-12',
    month: 'September',
    profileName: 'miahs05',
    clientUserId: 'jamshedtai2023',
    orderNumber: 'FO41C16CE2D84',
    amount: 200,
    netAmount: 160,
    assignedMembers: ['Jasmin'],
    estimatedDeliveryDate: '2026-09-20',
    deliveryDate: '2026-09-22',
    remark: 'Repeat Order',
    orderStatus: 'Wip',
    sheetLink: '',
    teamName: 'EleSquad',
    percentage: 40,
    note: '',
    userEmail: 'alirejakhan36@gmail.com',
  },
];

export async function POST() {
  try {
    await connectToDatabase();
    const count = await TeamProject.countDocuments();
    if (count === 0) {
      const normalized = SEED_TEAM_PROJECTS.map((p) => {
        p.month = getMonthFromDate(p.assignDate, p.month);
        return p;
      });
      await TeamProject.insertMany(normalized);
      return NextResponse.json({ success: true, message: `Seeded ${normalized.length} team orders from SMT EleSquad sheet` });
    }
    return NextResponse.json({ success: true, message: 'Team database already contains records', count });
  } catch (error) {
    console.error('Seed team projects error:', error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
