import { NextResponse } from 'next/server';
import connectToDatabase from '@/lib/db';
import Project from '@/models/Project';

const initialProjects = [
  {
    assignDate: "2026-03-30",
    month: "April",
    clientUsername: "mharris4463",
    profileName: "LeadsBridge",
    instructionSheet: "https://docs.google.com/document/d/WordPress_mharris4463",
    amount: 200,
    orderStatus: "Done",
    ourSubdomain: "https://mharris4463.wpcoreweb.com/",
    deadline: "2026-04-19",
    timeSchedule: "Complete",
    clientDomain: "https://naturalbeautyforliving.com",
    marketplaceStatus: "Delivered",
    dailyUpdate: "Solved",
    backupInfo: "Full cPanel backup created on Google Drive",
    review: 5,
  },
  {
    assignDate: "2026-04-07",
    month: "April",
    clientUsername: "timkasper",
    profileName: "W3b_Hive",
    instructionSheet: "https://docs.google.com/spreadsheets/d/timkasper_brief",
    amount: 100,
    orderStatus: "Done",
    ourSubdomain: "",
    deadline: "2026-05-04",
    timeSchedule: "Complete",
    clientDomain: "https://tmkspr.com/",
    marketplaceStatus: "Delivered",
    dailyUpdate: "Solved",
    backupInfo: "Theme & DB export saved",
    review: 5,
  },
  {
    assignDate: "2026-04-08",
    month: "April",
    clientUsername: "budinasgost7",
    profileName: "UIDesignli",
    instructionSheet: "https://docs.google.com/document/d/budinasgost7_spec",
    amount: 200,
    orderStatus: "Issue",
    ourSubdomain: "https://budinasgost7.wpelemburg.com/",
    deadline: "2026-04-19",
    timeSchedule: "Late",
    clientDomain: "",
    marketplaceStatus: "Cancel",
    dailyUpdate: "Solved",
    futurePlan: "Awaiting client response for domain DNS",
    review: 0,
    notes: "Client requested refund due to delay",
  },
  {
    assignDate: "2026-04-11",
    month: "April",
    clientUsername: "alpsjuve",
    profileName: "Codesilly",
    instructionSheet: "https://docs.google.com/spreadsheets/d/alpsjuve_ecommerce",
    amount: 350,
    orderStatus: "Wip",
    ourSubdomain: "https://alpsjuve.wpelemburg.com/",
    deadline: "2026-06-18",
    timeSchedule: "Late",
    clientDomain: "https://newsite.dnaarch.com/",
    marketplaceStatus: "Wip",
    dailyUpdate: "Product filter bug under investigation",
    futurePlan: "Deploy payment gateway",
    review: 0,
  },
  {
    assignDate: "2026-04-15",
    month: "April",
    clientUsername: "hfhdirect",
    profileName: "Sales_Handy",
    instructionSheet: "https://docs.google.com/document/d/Wordpress_hfhdirect",
    amount: 500,
    orderStatus: "Done",
    ourSubdomain: "https://hfhdirect.wpelemburg.com/",
    deadline: "2026-04-29",
    timeSchedule: "Complete",
    clientDomain: "",
    marketplaceStatus: "Delivered",
    dailyUpdate: "Completed all revisions",
    backupInfo: "WP All-in-One Migration file on server",
    review: 5,
  },
  {
    assignDate: "2026-04-16",
    month: "April",
    clientUsername: "shaleshasmith",
    profileName: "WpStellar",
    instructionSheet: "https://docs.google.com/document/d/349-shaleshasmith-brief",
    amount: 349,
    orderStatus: "Delivered",
    ourSubdomain: "https://patrick.teamcodexora.com/",
    deadline: "2026-05-14",
    timeSchedule: "Late",
    clientDomain: "",
    marketplaceStatus: "Delivered",
    dailyUpdate: "Submitted delivery files",
    review: 5,
  },
  {
    assignDate: "2026-04-23",
    month: "April",
    clientUsername: "manu0548",
    profileName: "WpStellar",
    instructionSheet: "https://docs.google.com/document/d/WordPress_manu0548",
    amount: 500,
    orderStatus: "Done",
    ourSubdomain: "https://manu0548.teamcodexora.com/",
    deadline: "2026-05-23",
    timeSchedule: "Complete",
    clientDomain: "",
    marketplaceStatus: "Delivered",
    dailyUpdate: "Delivered and verified",
    review: 5,
  },
  {
    assignDate: "2026-04-27",
    month: "April",
    clientUsername: "ryanmoore772",
    profileName: "Smtechnol...",
    instructionSheet: "https://docs.google.com/document/d/ryanmoore772_P02",
    amount: 450,
    orderStatus: "Wip",
    ourSubdomain: "https://ryanmoore772.teamcodexora.com/",
    deadline: "2026-06-23",
    timeSchedule: "Late",
    marketplaceStatus: "Wip",
    dailyUpdate: "Custom hero section coding in progress",
    review: 0,
  },
  {
    assignDate: "2026-05-09",
    month: "May",
    clientUsername: "drewfino",
    profileName: "WPRiders",
    instructionSheet: "https://docs.google.com/document/d/drewfino-wpriders",
    amount: 450,
    orderStatus: "Done",
    ourSubdomain: "https://drewfino.teamcodexora.com/",
    deadline: "2026-05-21",
    timeSchedule: "Complete",
    marketplaceStatus: "Delivered",
    review: 5,
  },
  {
    assignDate: "2026-05-21",
    month: "May",
    clientUsername: "jamesanthony25",
    profileName: "LeadsBridge",
    instructionSheet: "https://docs.google.com/document/d/jamesanthony25",
    amount: 280,
    orderStatus: "Done",
    ourSubdomain: "https://jamesanthony25.wpendgame.com",
    deadline: "2026-06-14",
    timeSchedule: "Complete",
    marketplaceStatus: "Delivered",
    review: 5,
  },
  {
    assignDate: "2026-05-22",
    month: "May",
    clientUsername: "edermartinez",
    profileName: "miahs05",
    instructionSheet: "https://docs.google.com/document/d/WordPress_edermartinez",
    amount: 150,
    orderStatus: "Done",
    ourSubdomain: "https://edermartinez.wpendgame.com",
    deadline: "2026-06-11",
    timeSchedule: "Complete",
    marketplaceStatus: "Delivered",
    review: 5,
  },
  {
    assignDate: "2026-05-25",
    month: "May",
    clientUsername: "kishanachang",
    profileName: "WPRiders",
    instructionSheet: "https://docs.google.com/document/d/WordPress_kishanachang",
    amount: 200,
    orderStatus: "Done",
    ourSubdomain: "https://kishanachang.wpendgame.com/",
    deadline: "2026-06-04",
    timeSchedule: "Complete",
    marketplaceStatus: "Delivered",
    review: 5,
  },
  {
    assignDate: "2026-05-28",
    month: "May",
    clientUsername: "kishanachang (Repeat)",
    profileName: "WPRiders",
    amount: 140,
    orderStatus: "Done",
    timeSchedule: "Repeat Order",
    marketplaceStatus: "Delivered",
    review: 5,
  },
  {
    assignDate: "2026-05-29",
    month: "May",
    clientUsername: "paulsneep",
    profileName: "Web_Spero_Fiverr",
    amount: 300,
    orderStatus: "Done",
    timeSchedule: "Complete",
    marketplaceStatus: "Delivered",
    review: 5,
  },
  {
    assignDate: "2026-05-30",
    month: "May",
    clientUsername: "paulsneep (Add-on)",
    profileName: "Web_Spero_Fiverr",
    amount: 280,
    orderStatus: "Done",
    timeSchedule: "Add-on",
    marketplaceStatus: "Delivered",
    review: 5,
  },
  {
    assignDate: "2026-06-02",
    month: "June",
    clientUsername: "jordimaasdam",
    profileName: "Miahs05_Fiverr",
    instructionSheet: "https://docs.google.com/document/d/WordPress_jordimaasdam",
    amount: 390,
    orderStatus: "Wip",
    ourSubdomain: "https://jordimaasdam.wpelemburg.com/",
    deadline: "2026-06-28",
    timeSchedule: "Late",
    marketplaceStatus: "Wip",
    dailyUpdate: "Elementor custom template design in progress",
    notes: "Assigned to Alireja/Shihad (EleSquad)",
    review: 0,
  }
];

export async function POST() {
  try {
    await connectToDatabase();
    const count = await Project.countDocuments();
    if (count === 0) {
      await Project.insertMany(initialProjects);
      return NextResponse.json({ success: true, message: `Seeded ${initialProjects.length} initial projects` });
    }
    return NextResponse.json({ success: true, message: `Database already contains ${count} projects` });
  } catch (error) {
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
